spring:
  application:
    name: liquibase-starter
  
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase_starter
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      "[hibernate]":
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  level:
    "[org.liquibase]": DEBUG
    "[org.springframework.jdbc]": DEBUG
